Name:           perl-Business-ISMN
Version:        1.11
Release:        1%{?dist}
Summary:        Work with International Standard Music Numbers
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Business-ISMN/
Source0:        http://www.cpan.org/authors/id/B/BD/BDFOY/Business-ISMN-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Tie::Cycle)
Requires:       perl(List::Util)
Requires:       perl(Test::More)
Requires:       perl(Tie::Cycle)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

Patch0:         %{name}-fix-package.patch

%description
Methods

%prep
%setup -q -n Business-ISMN-%{version}
%patch0 -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes ismns.txt LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Aug 22 2012 Mary Ellen Foster <mefoster@gmail.com> 1.11-1
- Specfile autogenerated by cpanspec 1.78.
