Name:           perl-XML-Writer-String
Version:        0.1
Release:        5%{?dist}
Summary:        Capture output from XML::Writer module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XML-Writer-String/
Source0:        http://www.cpan.org/authors/id/S/SO/SOLIVER/XML-Writer-String-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(strict)
BuildRequires:  perl(Test)
BuildRequires:  perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       perl(XML::Writer)

%description
This Perl module implements a bare-bones class specifically for the purpose
of capturing data from the XML::Writer module.  XML::Writer expects an
IO::Handle object and writes XML data to the specified object (or STDOUT)
via its print() method.  This module simulates such an object for the
specific purpose of providing the required print() method.

%prep
%setup -q -n XML-Writer-String-%{version}

%build
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
make %{?_smp_mflags}
sed -i 's/\r$//' String.pm README Changes example/*

%install
make pure_install DESTDIR=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes README example
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Nov 19 2014 Colin B. Macdonald <cbm@m.fsf.org> 0.1-5
- minor edits from review.

* Wed Nov 19 2014 Colin B. Macdonald <cbm@m.fsf.org> 0.1-4
- clean-up following review, added dep on XML::Writer.

* Tue Nov 18 2014 Colin B. Macdonald <cbm@m.fsf.org> 0.1-3
- rev bump to force copr rebuild on Fedora 21.

* Wed Aug 22 2012 Mary Ellen Foster <mefoster@gmail.com> 0.1-1
- Specfile autogenerated by cpanspec 1.78.
